### ISSUE TITLE
Is Refills included in this package?

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#102]
Hi there, I've tried adding the code for a refills navigation to a website which is using Some like it neat, but its just unstyled, non functional - should I be adding it in separately or something?

**Comment by digisavvy** [comment]
Wow buddy. Sorry for such a laggy response. No, SLiN doesn't use refills. But I have used the patterns from Refills on other projects. I usually create separate sass files for any styles and I'll run a single .js file where i'll place any relevant javascript.
