### ISSUE TITLE
Missing production.js & development.js from this version

### ISSUE THREAD

**Issue by Henry-Cullen** [digisavvy/some-like-it-neat#108]
Hi 
I'm just getting started with bourbon & neat and I may well be asking a dumb question.
I first found S.L.I.N. in the WP repository, and then here, but the 2 versions are quite different in their directory structure.

That's fine I woudn't always expect them to be the same, but when I put my S.L.I.N. master version ( from here ) into DEBUG I noticed 404's coming from a missing development.js file

So I checked in the js directory and sure enough it wasn't there, so I checked functions.php and saw the conditional calling it if I was in DEBUG mode.

So I checked both SLIN versions functions.php files in case I had mixed things up somehow, but they appear to be the same, both calling for production.js if not in DEBUG and development.js if DEBUG is true.

I noticed this because the local site I was working on was pretty slow and I had a nasty white screen flash on each page load. but apart from some very small adjustments to the header it was empty, with no plug ins, so it should be lightning fast.

I dug out the production.js from the WP version and that has solved my white flash and speed issue, but the development.js is still missing.

Whats the story there?
Simple oversight or deliberate and I am being a numpty?

Thanks
H

**Comment by televators** [comment]
I just got started with S.L.I.N. today and am having the same issue. Pretty annoying, right? I'm pretty much where you were when you posted. Have you found a fix yet? I'm wayyyy behind on a client's work and I NEEEEED this to be smooth and working. I guess I'll try out your method of using the production.js until it's fixed.

**Comment by digisavvy** [comment]
For other folks who may run into this issue, it's been resolved here: https://github.com/digisavvy/some-like-it-neat/commit/3c3e6e961a9fcb6b5d2ab425203a6e4f133df177
