### ISSUE TITLE
File to import not found

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#109]
Hi there,

I just tried using a fresh copy of the theme and when I'm trying to run gulp it keeps throwing back lots of files missing...

Looks like its trying to find a bourbon-neat folder that doesnt exist in node_modules

Like I say I've not changed anything, its  a fresh theme install

**Comment by millo2k** [comment]
Still the same as far as I can tell

**Comment by televators** [comment]
Looks like @digisavvy hasn't been active on here since last fall. What OS are you on? I might be able to help in the mean-time.

**Comment by digisavvy** [comment]
Hey folks, I got around to taking a look at this issue a bit more. This may be an uglier way of dealing with this.

`
        $directory = get_template_directory() . '/assets/js/app/';
        $files = glob($directory . '*.js');
        if ( $files !== false )
        {
            $filecount = count( $files );

            if ( ! $filecount == 0 ) {
                if ( SCRIPT_DEBUG || WP_DEBUG ) :

                    // Concatonated Scripts
                    wp_enqueue_script( 'some_like_it_neat-js', get_theme_file_uri( '/assets/js/development.js' ), array( 'jquery' ), '1.0.0', false );
                else :
                    // Concatonated Scripts
                    wp_enqueue_script( 'some_like_it_neat-js', get_theme_file_uri( '/assets/js/production-min.js' ), array( 'jquery' ), '1.0.0', false );
                endif;
            }
        }
`

**Comment by digisavvy** [comment]
The above code should be used to replace the existing SCRIPT_DEBUG calls.

**Comment by digisavvy** [comment]
Hey folks, this has been resolved. So sorry for the delay here.
