### ISSUE TITLE
CSS breaks after update to 1.5.0

### ISSUE THREAD

**Issue by crbarnett** [digisavvy/some-like-it-neat#117]
The version 1.3.8 we have running on the [live site is working](http://www.asalesguy.com/).

We've cloned the site to a [staging environment](http://asalesguy.staging.wpengine.com/), installed the latest 1.5.0 theme package, and upon activating the new version there seems to be no CSS rendered on the page.

The site is hosted on WP Engine, where we don't have access to command line tools. They could not find any clues as to why this wasn't working. But, they did say that sass has not been installed.

I hinted that not having sass might be the issue... alas no luck. Any help is appreciated.

**Comment by digisavvy** [comment]
Hey @crbarnett -
Best thing to do is to run gulp on your local setup, it will generate the necessary CSS files for you, then upload those to your staging server.
