### ISSUE TITLE
Which branch should I start with

### ISSUE THREAD

**Issue by amklose** [digisavvy/some-like-it-neat#118]
Hi there, I would like to try this theme and create a child theme from it, but I see the development branch is 250 commits ahead of master. Is the development branch ok to use on a production site or are there any major bugs that you're aware of?

**Comment by digisavvy** [comment]
Per my comment in https://github.com/digisavvy/some-like-it-neat/issues/119 start with `master`. However, development will always be the most current branch and is typically stable.
