### ISSUE TITLE
headroom not found

### ISSUE THREAD

**Issue by amklose** [digisavvy/some-like-it-neat#119]
When I try running gulp for the first time, it errors out because it can't find the "headroom" scss that is being imported into /assets/sass/vendor/__vendor-dir.scss

I can't find anywhere where it's loading that library. Should that be in composer.json or package.json somewhere?

**Comment by digisavvy** [comment]
oh man, super sorry @amklose. Probably not using this now are ya? I fixed this issue. My .gitignore needed to be adjusted. I pushed up the latest version to the master branch, which is what you should use.
