### ISSUE TITLE
crashes wordpress after activation

### ISSUE THREAD

**Issue by kevincompton** [digisavvy/some-like-it-neat#120]
I've tried repeated installs and variations on the variables in the gulp settings and no matter what activating this theme crashes my local wordpress install completely and only works again if I unset that theme in the database

**Comment by digisavvy** [comment]
Hi @kevincompton -
Sorry for the troubles there. Can you provide me some steps so I can attempt to reproduce? Also, is this a fresh install? What error do you receive when you activate the theme?

**Comment by digisavvy** [comment]
@kevincompton - just checking in on those steps. Let me know. =)

**Comment by digisavvy** [comment]
@kevincompton - I did end up replicating this issue. Or at least I think I did. You have to run `composer install` first. At least for now. I'll work that issue out and/or update the documentation.

**Comment by digisavvy** [comment]
Hi @kevincompton - this [PR](https://github.com/digisavvy/some-like-it-neat/pull/121) from @bamadesigner should address this issue. Let me know if it's still an issue for you.

Thanks.
