### ISSUE TITLE
Full width columns

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#17]
Whats the best way to make a three column container full width? So that the three columns take up the full width of screen (no margins between each column).

Thanks

**Comment by millo2k** [comment]
I've come back to this again.... the omega mixin takes away the margin from the right of the first but it then moves the left container over up against the left left column (as it should), it then leaves a space to the right of the right column???

**Comment by digisavvy** [comment]
If you define omega like `@include omega(block);` it removes the margin on the given element you're using it in. 

In this example, omega would remove margins/gutters on any element with the .col style assigned to it. I want to say.
Here's what it looks like: https://www.evernote.com/shard/s2/sh/d39637ec-0b9f-4cf0-9319-8f5e1369c163/7b95c61bb122c45918bbacee42901360
`.col {
	span-colums(2);
}`

In this example, I'm targeting the 3rd element, and this would happen every third element
Note the lack of a margin in the third column: https://www.evernote.com/shard/s2/sh/f2ff5edc-9891-4176-92eb-9228e3679925/6a0b36bc75550a4d8cd5d7a007c17ff0
`.one-third {
	background: #ccc;
	@include span-columns( 3 );
	@include omega( 3n );
}`

You can target any element and remove it's margin/gutter. If you don't specify anything using omega, all elements' gutters/margins are removed. 

Does that help?
