### ISSUE TITLE
Use get_stylesheet_uri()

### ISSUE THREAD

**Issue by justintadlock** [digisavvy/some-like-it-neat#41]
The primary stylesheet URI for the theme should utilize the `get_stylesheet_uri()` function. Some plugins (and even child themes) might rely on the `get_stylesheet_uri` filter hook.

If, for some reason, you don't want the `style.css` file to load, you can filter `get_stylesheet_uri` to return a file of your choice.  The important part is that the hook is executed.

**Comment by digisavvy** [comment]
Do you mean get_stylesheet_directory_uri()? I'm assuming as much.

**Comment by justintadlock** [comment]
No, I mean `get_stylesheet_uri()`, which is a different function.  It's the function for loading the theme stylesheet.  `get_stylesheet_directory_uri()` is for referencing the stylesheet directory.

Reference: http://codex.wordpress.org/Function_Reference/get_stylesheet_uri
