### ISSUE TITLE
Yoda conditions

### ISSUE THREAD

**Issue by justintadlock** [digisavvy/some-like-it-neat#45]
There are places in the theme that should use Yoda conditions.  Reference: https://make.wordpress.org/core/handbook/coding-standards/php/#yoda-conditions

Basically, you need to flip your if statement checks around.  For example:

	if( get_theme_mod( 'digistarter_mobile_hide_arrow' ) == 0 ) { ?>

Should be:

	 if ( 0 == get_theme_mod( 'digistarter_mobile_hide_arrow' ) ) { ?>

I'll link to the ones I catch, but it's worth going through the code to make sure we're not missing any.

* https://github.com/digisavvy/some-like-it-neat/blob/master/functions.php#L209
* https://github.com/digisavvy/some-like-it-neat/blob/master/functions.php#L226

**Comment by digisavvy** [comment]
Thanks for this
