### ISSUE TITLE
Title tag

### ISSUE THREAD

**Issue by justintadlock** [digisavvy/some-like-it-neat#46]
WP 4.1 introduced the `title-tag` theme support feature.  Use it over `wp_title()`.  See: http://codex.wordpress.org/Title_Tag

**Comment by justintadlock** [comment]
Is this the issue you asked about via email?  Did you make sure to remove this line of code from `header.php`?

	<title><?php wp_title( '|', true, 'right' ); ?></title>

**Comment by digisavvy** [comment]
Hey there, it is the issue and I did do that first thing, but the issue persists... I might have to git bisect this guy, too.
