### ISSUE TITLE
"Proudly powered" footer text

### ISSUE THREAD

**Issue by justintadlock** [digisavvy/some-like-it-neat#48]
In `footer.php`, you have this text:

	<?php printf( __( 'Proudly powered by <span class="genericon genericon-wordpress"></span> %s', 'digistarter' ), 'WordPress' ); ?>

There are a couple of issues worth thinking about with this.  1) Always avoid HTML in translations if possible (things can get messed up).  2) It's OK to allow "WordPress" to be translated.

There are a couple of options to consider.  The first is my preference:

	<?php printf( __( 'Proudly powered by %s WordPress', 'digistarter' ), '<span class="genericon genericon-wordpress"></span>' ); ?>

	<?php _e( 'Proudly powered by <span class="genericon genericon-wordpress"></span> WordPress', 'digistarter' ); ?>

**Comment by digisavvy** [comment]
Thank you! Learning all sorts of new stuff.
