### ISSUE TITLE
Separate scripts should go in separate files

### ISSUE THREAD

**Issue by justintadlock** [digisavvy/some-like-it-neat#50]
While it does make some sense to combine all JavaScript into a single file in one way, it also makes it extremely hard to do anything else.  The problems with combination are twofold:

* Child theme users can't dequeue or replace a specific script.
* It doesn't play nicely with other plugins (e.g., plugin + theme loading Flex Nav).

Also, there are plugins available to concatenate and generally speed things up.

**Comment by digisavvy** [comment]
Thanks for this explanation, J-money. =)

It makes total sense and I am in agreement and have made this change. Thank you!
