### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by koraysels** [digisavvy/some-like-it-neat#56]
I've installed everything ran ```npm install```, ```bower install``` and ```gulp``` but i still get javascript errors ... any ideas? did I forget something?

**Comment by digisavvy** [comment]
Sorry you're having issues with the theme, man. =)

So, upon installing the theme, run npm install (or sudo npm install, if it needs to be ran as an admin on a mac), and then bower install will get you up and going. Once that's done, you need to just run 'gulp' without the single quotes.

At which point do you see that error?

**Comment by koraysels** [comment]
When I run the theme.. I mean js errors in the chrome console saying "define is not defined".. I switched to an older version of your theme and there are no problems there;) thanks for your work!

**Comment by digisavvy** [comment]
Hey there,
Hmm, I'd like to be able to reproduce the issue, but I'm not able to, even on the latest version of the theme... Do you recall the version that was giving you fits?
