### ISSUE TITLE
Unhandled throw error on gulp default task run

### ISSUE THREAD

**Issue by RyanHipkiss** [digisavvy/some-like-it-neat#59]
Hey, 

Upon downloading the latest repository, I installed everything and ran the default gulp task. 

However this threw an error at me. 

events.js:72 
throw er;

//Unhandled throw error;

Sorry there isn't much information here, I can add more if needs be, I just only remembered to submit this issue and I am away from my computer atm.

**Comment by RyanHipkiss** [comment]
Ignore this. It's probably the fact I don't have bower or composer installed on that computer yet. I've just read the README again! D'oh!

**Comment by digisavvy** [comment]
Haha. No worries, I was just going to ask if you'd run bower, even I ran into that issue just the other day. =) Let me know how you get sorted out!

**Comment by RyanHipkiss** [comment]
Yep. I needed to install bower. Note to self - read the README.md
