### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#60]
Not sure if this is something I'm doing (or not doing)... But with the newer template (with bower and composer), terminal is throwing up an error. All is fine if updating styles, but the moment I update the page template I get this error in my terminal...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)

It then stops updating my styles from here or in.... I have to shut down terminal and reload

Any ideas?

Thanks

**Comment by digisavvy** [comment]
Sorry you're running into an issue there!

I ran into this, too. Make sure to run bower install in your theme's root dir.

If the issue is still happening, screenshot your theme directory, with the bower folder open.
