### ISSUE TITLE
Yeoman Generator

### ISSUE THREAD

**Issue by desaiuditd** [digisavvy/some-like-it-neat#61]
Hey, @digisavvy 

I checked out the roadmap for the theme and saw that you've Yeoman Generator for Some Like It Neat in pipeline.

I've kind of worked upon the same lines and created yeoman generator for this theme.

https://github.com/moxienyc/generator-moxie-wp

Would you mind taking a look at it. Looking forward to collaboration. :smiley: 

CC: @jeffreynolte

**Comment by digisavvy** [comment]
Oh cool! =) I'll give it a test spin this week for sure.

**Comment by jeffreynolte** [comment]
@digisavvy - We also have a bunch of common tasks in our cue for the generator we will be working on relatively soon, some are handled in the theme but I feel we will likely handle some of the setup in the generator depending on where it makes sense to place the logic (theme or generator).  Would love your input and look forward to collaborating more :+1:

**Comment by digisavvy** [comment]
So I played with this and I liked what it did. I'm just not sure how this saves me time, over what I'm already doing... That said, I'm happy help and what not, I think it's pretty darn cool in my book.

I guess I'd want to know what the setup looks like as a whole. Is this a part of a greater installation that requires composer to download all the stuff, which creates your wp install or theme install etc. Does that make sense?
