### ISSUE TITLE
browsersync: 'localhost:3000' shows apache default page.

### ISSUE THREAD

**Issue by sunilw** [digisavvy/some-like-it-neat#65]
Great that there's a wp starter theme with bourbon. Saves me from building one myself!

When I run 'gulp' the browsersync task starts to run.
If I navigate to 'localhost:3000' I get the "Apache Debian Default Page". It looks like I've navigated to an unconfigured vhost.

Navigating to 'localhost:3001' takes me to the options page for browsersync. So I know that browsersync is actually working.

I can see that browsersync has conf options for working with pre-existing servers using something called "proxy-mode", but I can't see how to integrate those options with gulp config bundled with somelikeitneat.

Should the browsersync/gulp config bundled with somelikeitneat work out of the box? Or am I missing something in the installation process?

**Comment by digisavvy** [comment]
Hey there. Sorry you're having issues with the theme. You exposed one area that was sorta haphazardly conceived. In short, it's not you, it's totally me. =)

I'm going to upload an update here and address that. Basically, in your gulp file there is a project configuration area. There's a config for your local site's URL string, which is passed to the browser-sync task. Once you pass the appropriate URL string then the site should load just fine. Stay tuned.

**Comment by sunilw** [comment]
Hey Alex!
Thanks for starting to address this.

I'll stay tuned. Let me know if you need any help testing.

**Comment by digisavvy** [comment]
Hey there,
This should be good to go if you want to give it a run. In gulpfile.js just be sure to set your project URL, without the http:// prefix of course. Let me know if that sorts you out! =)

**Comment by sunilw** [comment]
I nuked the theme dir that I'd built from some-like-it-neat. I then cloned latest. Installed the node and bower packages, edited 'project' var in gulpfile...

... and it all works with browsersync!

Thanks Alex!

**Comment by digisavvy** [comment]
Awesome. Thanks for the update!

**Comment by sunilw** [comment]
Hey Alex.

After a git pull from master this issue has risen again.

**Comment by sunilw** [comment]
I'm mistaken.

I had neglected to edit the 'url' value in gulpfile.js
