### ISSUE TITLE
feature request: editorconfig file

### ISSUE THREAD

**Issue by sunilw** [digisavvy/some-like-it-neat#68]
Hey Alex.
I *might* end up contributing code back.

I've forked and I'll basically be modifying the project to match my favoured settiings for a project starter.
However I'm basically using the per-language defaults of my editor - gnu emacs.
I swear, if you want to pull any of my changes in, you are going to be annoyed that many of the files will be exactly the same except for indentation.

If you haven't seen editorconfig before: http://editorconfig.org/

**Comment by digisavvy** [comment]
Hey Sunil,
Sorry for the lag here. I'm definitely open to this, if you're still interested. I'll close this for now. Should you decide to contribute an editorconfig file, please do so on the dev branch
