### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ginblue** [digisavvy/some-like-it-neat#69]
Getting an error when running gulp build.

Don't think this is a theme issue, just hoping someone has come across it and has a solution. Think it maybe some kind of permission issue but not sure. 

More designer than developer and never used these build tools before, so please forgive me if i've missed the obvious.

C:\Program Files\Ampps\www\retro-events-SLiN\wp-content\themes\retroevents>gulp
build
[17:19:10] Using gulpfile C:\Program Files\Ampps\www\retro-events-SLiN\wp-conten
t\themes\retroevents\gulpfile.js
[17:19:10] Starting 'build'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task trigger
ing instead.
[17:19:10] Starting 'cleanup'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EPERM, unlink 'C:\Program Files\Ampps\www\retro-events-SLiN\wp-content\th
emes\retroevents\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32
-node-0.12\binding.node'
  at Error (native)

Thanks Anthony

**Comment by digisavvy** [comment]
WOrking on this, Anthony. Thanks for reporting.

**Comment by digisavvy** [comment]
The latest development push should contain a fix for this that you can try out. You can copy the gulpfile.js  contents to your current project to see if that helps
