### ISSUE TITLE
legacy filter for page title

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#72]
Could you let me know where the legacy filter is thats adding a second page title. If at all possible I want to avoid pulling a new version of the theme.

Thanks

**Comment by digisavvy** [comment]
Sure. Check out this commit: https://github.com/digisavvy/some-like-it-neat/commit/e87f864a358c2f788092d0a63546470301ce1be1 and look at the extra.php file there for the wp_title function. Hopefully that gets you sorted out.
