### ISSUE TITLE
BrowserSync Issue

### ISSUE THREAD

**Issue by onlyskyguy** [digisavvy/some-like-it-neat#74]
I get the below error after running the default task. It's triggered by the line:gulp.watch(source+'js/app/**/*.js', ['js', browserSync.reload]);
Anyone have any ideas why browserSync.reload is doing this?

/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true)
                 ^
TypeError: Cannot read property 'fragmentedOperation' of null
  at Receiver.endPacket (/media/orestis/Files/Documents/Projects/Coding/WP/vagrant-local/www/onlysky/htdocs/wp-content/themes/onlysky_d/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222:18)
  at Receiver.opcodes.1.finish (/media/orestis/Files/Documents/Projects/Coding/WP/vagrant-local/www/onlysky/htdocs/wp-content/themes/onlysky_d/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:394:12)
  at Receiver.<anonymous> (/media/orestis/Files/Documents/Projects/Coding/WP/vagrant-local/www/onlysky/htdocs/wp-content/themes/onlysky_d/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:372:33)
  at Receiver.add (/media/orestis/Files/Documents/Projects/Coding/WP/vagrant-local/www/onlysky/htdocs/wp-content/themes/onlysky_d/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:87:24)
  at Socket.firstHandler (/media/orestis/Files/Documents/Projects/Coding/WP/vagrant-local/www/onlysky/htdocs/wp-content/themes/onlysky_d/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)

**Comment by digisavvy** [comment]
That's definitely an odd one. Can you post your gulpfile?

Another quick thing to try is to update the BrowserSync package.

**Comment by onlyskyguy** [comment]
Haven't modified the gulpfile beyond changing the local development url. I'm running VVV (vagrant) for the development server on my machine. Could there be a problem with this?

**Comment by digisavvy** [comment]
I've never tested w/ VVV to be honest, so I imagine that would definitely need to be taken into consideration; you might need to modify your config. Have a look at this topic: https://github.com/BrowserSync/browser-sync/issues/284 - But from what I've seen folks have been able to set it up; at some point I'll test with that config.

**Comment by onlyskyguy** [comment]
Ugh, now getting this error randomly:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at WriteWrap.afterWrite (net.js:766:14)

**Comment by onlyskyguy** [comment]
@digisavvy Any idea on the above?

**Comment by digisavvy** [comment]
The error seems to indicate a possible linting error. So I'm curious if you're using any custom javascript in your project. The linter will check files placed in assets/js/app

**Comment by onlyskyguy** [comment]
I just cloned the repo and ran gulp

**Comment by digisavvy** [comment]
Hmm. Before running gulp, I'm assuming you rand  'npm install,' in addition you need to run 'bower install' and then 'php composer.phar install'. Can you confirm each of those ran okay?

**Comment by onlyskyguy** [comment]
Yes did all of these. Also I just tried running gulp browser-sync by itself and I haven't gotten the error ...yet.

**Comment by digisavvy** [comment]
To quote my man, Clay Davis, "Sheeeeeiiiiiiiiiiiiiiiiiiiiiiiiiit..." 

I'm curious if you can pinpoint a specific task that is throwing out the error. I'm not able to replicate, but if we can track down the task and related packages that could be a good start.

**Comment by digisavvy** [comment]
Well, many of the packages also need an update, too. 

```
"gulp-install" can be updated from ^0.2.0 to ^0.4.0 (Installed: 0.2.0, Latest: 0.4.0)
"browser-sync" can be updated from ^2.4.0 to ^2.7.1 (Installed: 2.7.1, Latest: 2.7.1)
"gulp-autoprefixer" can be updated from ^2.1.0 to ^2.2.0 (Installed: 2.2.0, Latest: 2.2.0)
"gulp-cache" can be updated from ^0.2.8 to ^0.2.9 (Installed: 0.2.9, Latest: 0.2.9)
"gulp-combine-media-queries" can be updated from ^0.1.0 to ^0.2.0 (Installed: 0.1.0, Latest: 0.2.0)
"gulp-imagemin" can be updated from ^0.6.2 to ^2.2.1 (Installed: 0.6.2, Latest: 2.2.1)
"gulp-jshint" can be updated from ^1.9.4 to ^1.10.0 (Installed: 1.10.0, Latest: 1.10.0)
"gulp-livereload" can be updated from ^2.1.1 to ^3.8.0 (Installed: 2.1.1, Latest: 3.8.0)
"gulp-load-plugins" can be updated from ^0.6.0 to ^0.10.0 (Installed: 0.6.0, Latest: 0.10.0)
"gulp-newer" can be updated from ^0.3.0 to ^0.5.0 (Installed: 0.3.0, Latest: 0.5.0)
"gulp-phpcs" can be updated from ^0.4.0 to ^0.6.0 (Installed: 0.4.0, Latest: 0.6.0)
"gulp-plumber" can be updated from ^0.6.6 to ^1.0.0 (Installed: 0.6.6, Latest: 1.0.0)
"gulp-rename" can be updated from ^1.2.0 to ^1.2.2 (Installed: 1.2.2, Latest: 1.2.2)
"gulp-rimraf" can be updated from ^0.1.0 to ^0.1.1 (Installed: 0.1.1, Latest: 0.1.1)
"gulp-sourcemaps" can be updated from ^1.5.1 to ^1.5.2 (Installed: 1.5.2, Latest: 1.5.2)
"gulp-uglify" can be updated from ^1.1.0 to ^1.2.0 (Installed: 1.2.0, Latest: 1.2.0)
"gulp-zip" can be updated from ^2.0.3 to ^3.0.2 (Installed: 2.0.3, Latest: 3.0.2)
```

**Comment by onlyskyguy** [comment]
Sadly, all that does is run the browser-sync task which just reloads the page when php files or images are changed.

I'm not getting anything else working (the important stuff) like injecting css, minifying, etc etc. 

What in this gulp config could cause gulp to break for me? I'm using everything out of the box without any change in config.

**Comment by onlyskyguy** [comment]
Ok I tried the gulp task without phpcs... and no error so far. That seems to be the crux of it.

**Comment by digisavvy** [comment]
Ah. Okay. Phpcs. So, what I've found is that you need to add the location of PHPCS to your environment $PATH. Not sure if you're on windows, mac or something else, but if you do that, you should be sorted.
