### ISSUE TITLE
Body color in ltr and rtl

### ISSUE THREAD

**Issue by bjorn2404** [digisavvy/some-like-it-neat#79]
I'm probably just misunderstanding how this is set up but I can't figure out why the body color is set to #000 in @include ltr and @include rtl in /assets/sass/layouts/_structure.scss instead of using a color variable such as $base-font-color.

**Comment by digisavvy** [comment]
Hey there,
Thanks for creating this issue. You're not misunderstanding anything. I've gone through and updated the theme to make use of color variables, it had been on my 'to-do' for some time. Thanks for the nudge. =)

The update is in the dev branch right now. I'll merge into master soon.

**Comment by bjorn2404** [comment]
Great, thanks.
