### ISSUE TITLE
Issues with own js files.

### ISSUE THREAD

**Issue by mroesele** [digisavvy/some-like-it-neat#84]
Hi there, I am trying to get familiar with "some like it neat" and would like to use it in my latest wp project.
First of all, I am very impressed by this theme and the whole workflow. Thanks a lot for your great work.

But there is something I would like to share with you.
I had some troubles getting a simple js alert to work. 
I created a new js file and placed it in /assets/js/app/test.js

It took some minutes to figure out how this is meant to work.

* .jshintrc is lacking "devel": true, which will cause error messages while running gulp.
I was thinking about how this option could be dynamically added depending on the WP_DEBUG setting but I failed :)

* both development.js and production-min.js are not enabled in functions.php. The corresponding wp_enqueue_script() is deactivated and the wp_register_script call is missing completely.

I think the two generated js files should be enqueued by default:
<pre><code>// Concatenated Scripts
wp_register_script( 'development-js', get_template_directory_uri() . '/assets/js/development.js', array( 'jquery' ), '1.0.0', false );
wp_enqueue_script( 'development-js', get_template_directory_uri() . '/assets/js/development.js', array( 'jquery' ), '1.0.0', false );
</code></pre>

* /assets/js/app/readme.md should be more clearly:

<code>
"You don't need to link to files placed in this folder. Instead, link to either production.js or development.js files."</code>
 --> 
<code>
"You don't need to link to files placed in this folder. Instead, link to either production.js or development.js files in functions.php or directly in your markup"</code>

**Comment by louisnovick** [comment]
In the latest version they seem to be commented out in the functions.php file.  I suppose that's ok but I do agree that out of the box they should be active :)

**Comment by digisavvy** [comment]
@louisnovick @mroesele, I've heeded your input and these scripts are not available by default. =)

Thanks.

**Comment by hasnat-babur** [comment]
I am feared about the js task. They could be more flexible like Roots Sage.
