### ISSUE TITLE
Gulp file watcher only watches existing files

### ISSUE THREAD

**Issue by mroesele** [digisavvy/some-like-it-neat#85]
I have noticed that newly created assets like sass files do not trigger concatenation and browser reload while running gulp. After adding a new file you have to stop and restart the gulp task.
Can this be fixed somehow? Can someone help?

By the way, I am working with some like it neat for a few days and it really changed my workflow to the better. Thanks for the great work!

**Comment by digisavvy** [comment]
That's great. So far, this is an issue I cannot address. If you add a new file in sass, you have to stop and restart gulp for now anyway.

**Comment by hasnat-babur** [comment]
hi, just add an space or tab in your main or old scss file, then save, everything will work fine ...

**Comment by digisavvy** [comment]
@mroesele, @hasnat-babur's suggestion works, too. Hope that helps.

**Comment by hasnat-babur** [comment]
when you add a file ... pls do not use ./ before root folder, i.e. './assets/css/**/*.css' format, just use 'assets/css/**/*.css' as folder path and gulp will work for new files. It worked for me .. thanks
