### ISSUE TITLE
Composer.phar in Repo

### ISSUE THREAD

**Issue by dannywilson** [digisavvy/some-like-it-neat#87]
Hi,

I'm not sure why this is included in the repo? Seems a little weird since you should really be installing composer globally. If there is a reason this is included could you let me know? If not I'm more than happy to update the repo and send a PR.

Ta,
Danny

**Comment by digisavvy** [comment]
@dannywilson, sorry about that. I'd be happy to accept a PR (several months after your post), I didn't really know better honestly. LEt me know your thoughts there.

**Comment by digisavvy** [comment]
I've since removed composer from this project. At least for the time being. I'd like to figure out how best to handle certain tools like code sniffing and the like.
