### ISSUE TITLE
Does not work with node v4

### ISSUE THREAD

**Issue by prikkprikkprikk** [digisavvy/some-like-it-neat#89]
Upgrading to Node v4 breaks stuff horribly. I'm sorry I'm not competent enough to pinpoint what exactly …

**Comment by adrianocr** [comment]
I'm going to try to fix all the Node 4 issues and if I manage to I'll attempt to merge it back here.

**Comment by digisavvy** [comment]
I've been out and away on this, I'll be testing and see if I can resolve.

**Comment by digisavvy** [comment]
@prikkprikkprikk @adrianocr, I have resolved the Node 4x issues; SLIN does work with NPM 4 and 5 now. The issue boiled down to streaming with the combine media queries plugin; I replaced it with another one and that seemed to resolve the issue. Try it out. =)
