### ISSUE TITLE
gulp: command not found after going through all steps

### ISSUE THREAD

**Issue by siwise** [digisavvy/some-like-it-neat#91]
I have followed installation guide. But gulp command not found. Please help. If gulp is installed globally, gulp command works but styling doesn't get applied. I have tried everything workaround with no luck.

**Comment by wjramos** [comment]
Are you gulping from the theme root? you need to gulp within a directory with a gulpfile to instruct it what to do

**Comment by siwise** [comment]
I am gulping from the theme root with a gulpfile in that directory. Maybe I'm not using the correct versions of the other dependencies? What version of node and npm are recommended. I don't remember seeing this in documentation.

**Comment by digisavvy** [comment]
Hey guys,
I'm pushing up an update here shortly that "should" resolve these issues. Check the master branch and pull it down and try again.

**Comment by digisavvy** [comment]
@siwise - What version of Node are you using? Run 'node -v'.

**Comment by siwise** [comment]
I originally downloaded 4.2.2 from the link in documentation.

**Comment by digisavvy** [comment]
Ok, good! =)

So what happens when you run `npm install`?

**Comment by digisavvy** [comment]
@siwise just following up on this issue. Still having the problem?

**Comment by siwise** [comment]
Hi, Sorry for slow reply. I am still having the same issue. On npm install
i get these warnings -

npm WARN deprecated gulp-run-sequence@0.3.2: Renamed to run-sequence as
it's not really a gulp plugin.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained.
Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained.
Upgrade to lodash@^3.0.0.

and when running php composer.phar install i get:

Cannot create cache directory /Users/siwise/.composer/cache/repo/
https---packagist.org/, or directory is not writable. Proceeding without
cache.

but it still seems to install ok.

After everything is installed and I run 'gulp' it says no command found.

Even if I do npm install --save-dev gulp in my root folder, it still
doesn't cannot find gulp command.

I have tried on 2 different MBP on 10.10.5 and 10.11.1

Any other ideas?


Sorry to take your time.

**Comment by digisavvy** [comment]
Hmm interesting. So there is a newer version of SLIN if you want to download and try it out. It addresses the gulp run sequence warning—although that should cause an issue. In your Node Modules folder, do you see gulp in your list of folders? See here: https://www.evernote.com/l/AALISOyZ-_9Bo5FCiKFJWRIGsg3Yr1DWAMk — it seems that Gulp just isn't installing, which is odd.

And no worries at all, I'm just sorry this hasn't been working for you.

**Comment by siwise** [comment]
Gulp folders exist in Node Modules (see attached).
I am currently working with the Sage Theme which uses gulp fine. I wonder
why it isn't working with SLIN. SLIN sounds awesome, I was looking forward
to playing around with it.

I cloned SLIN from Github yesterday, would that be the new version?

**Comment by digisavvy** [comment]
I'm perplexed! Not sure why it's not doing it's thing. Can you post your gulp file here.

**Comment by siwise** [comment]
I haven't changed the gulp file except for the var project and var url.

**Comment by jjloomis** [comment]
Hi @siwise. Are you using NVM?

**Comment by siwise** [comment]
I used the standard version of node.js npm initially but when I couldn't get it to work I then changed to nvm to see if that changed anything. Any recommendations? 



—
Simon Wise

**Comment by jjloomis** [comment]
From an earlier post it looks like you installed 4.2.2. Make sure you that's your default version every time you open a terminal window by using nvm alias default 4.2.2. Then, in terminal, do a Command T to open a new terminal window. (Do an nvm ls to make sure 4.2.2 is your current version of node.js and your default.) In terminal, navigate to the root of your some-like-it-neat (or whatever you've called it) folder. Then do a sudo npm install -g gulp. (I had to use sudo.) Once that's done doing its thing, do gulp. 

From what I can tell, if you switch your version of node.js using NVM, you have to go through the npm install -g gulp process for whatever version of node.js you've switched to.

Let me know if this works (or if you've tried this stuff already.)
