### ISSUE TITLE
CodeKit Error 

### ISSUE THREAD

**Issue by jkinley** [digisavvy/some-like-it-neat#93]
I can't make edits to scss files. For example, _header.scss. CodeKit throws up an error: 

```
Error: File to import not found or unreadable: ../../assets/bower_components/bi-app-sass/bi-app/bi-app-ltr.
       Load paths:
         /Volumes/Data/jkinley/Sites/bourbon.dev/wp-content/themes/tipsy/assets/sass
         /Applications/CodeKit.app/Contents/Resources/engines/bourbon/bourbon/app/assets/stylesheets
         /Applications/CodeKit.app/Contents/Resources/engines/neat
         Sass::Globbing::Importer
        on line 1 of /Volumes/Data/jkinley/Sites/bourbon.dev/wp-content/themes/tipsy/assets/sass/style.scss
  Use --trace for backtrace.
```
What I notice is that it is complaining about bi-app-sass. Upon further inspection, I see that there is suppose to be a bower_components directory under assets in your folder structure diagram, but there is no such directory in the repository. I am pretty new with all these task runners and such, do I could be doing something very wrong. Hope my comments help.

**Comment by digisavvy** [comment]
@jkinley I wouldn't recommend using codekit with this theme. It's built for use with Gulp, which is like a command line version of codekit (and much cooler) =). What you're seeing is that your bower components haven't been installed. Refer to the readme and go through each installation step and then you should be set and ready to go. This theme has a few steps you need to go through before you can get full benefits.

**Comment by digisavvy** [comment]
I'm closing this one out.
