### ISSUE TITLE
Javascript development.js and production-min.js not being produced and zip not working

### ISSUE THREAD

**Issue by TimothyAFernandez** [digisavvy/some-like-it-neat#95]
Hey All!

I've been using "some-like-it-neat" for the development of a recent theme for a client and It's an incredible set of tools.

I am experiencing a couple of problems with the gulp commands, specifically when using "gulp build" unfortunately the development.js and minified production.js are not being produced and the file isn't zipping. 

I've installed gulp locally in the theme root folder and all other aspects are working fine just unsure what the problem is. Any help would be very much appreciated.

**Comment by playcodestudio** [comment]
I have the same problem, can anyone help us?

**Comment by digisavvy** [comment]
Sorry for the delay on this. Can you verify that this is still an issue? Try the development branch. I've been running through this and can't replicate the error. Any error messages will help. Thanks.

**Comment by playcodestudio** [comment]
I'm sorry for the delay to my reply.
I've installed again gulp and the theme (1.3.7) locally and all seems to work fine except the javascript (`development.js` and `production-min.js`) and custom javascript.

I created a custom js file (custom.js) in assets/js/app directory with this this code
```
/**
 * custom.js
 */
(function($) {
    alert("hello!");
})(jQuery);
```

When run Gulp, `development.js` and `production-min.js` files are created but the alert doesn't work... and in code view I see the development.MIN.js path with version (see this [screenshot](https://www.dropbox.com/s/ahxqltxmi0k5qh8/development.min.js_screenshot.jpg?dl=0)) but the file doesn't exist.

Can you explain me what's wrong and how to do this correctly?

Thank you!

**Comment by digisavvy** [comment]
Hey @playcodestudio, I think I may know what's wrong here. 

The logic loading the scripts was wrong. In a recent update a suffix was added to the development.js file, which was incorrect. I've fixed that. This should work as expected now.
