### ISSUE TITLE
Very Slow Gulp Process Even In High End PC

### ISSUE THREAD

**Issue by hasnat-babur** [digisavvy/some-like-it-neat#99]
Hi, 
First of all thanks for developing such beautiful starter theme.

I have noticed some important things with this some-like-it-neat starter theme.

Before this, I have tested Roots Sage starter theme, build tool like gulp works very fast out of the box with amazing features.

I am not getting proper compile speed using Some-Like-It-Neat anyway. I have heard this problem from others too.

It would be best if you modify gulpfile.js code so that we get proper build speed like Roots Sage. 
Cheers, Best Regards.

**Comment by digisavvy** [comment]
Hello @hasnat-babur, sorry you're seeing troubles there. I've ran both sage and my slin locally. Slin actually loads faster for me. I'd like to troubleshoot this further. 

How long does slin take to run through gulp?

**Comment by hasnat-babur** [comment]
Hi, Thanks for your reply. SLIN gulp works fine at initial. After working about an hours SLIN gulp process becomes very slow, sometimes only sass compile time takes 5-10 seconds, even sometimes take 15 seconds to complete sass compile. Although I am creating only one css, js file perspectively rather than creating both minified and develop version. Thanks.

**Comment by hasnat-babur** [comment]
Solved! Hi ... After installing SLIN, I updated node packages and everything works perfect and faster! Thanks a lot for this awesome extra ordinary starter theme. It's my choice for most large themes. Thanks.
